**Kütüphanelerin ve veri setinin yüklenmesi (Çalıştırmak için öncelikle dosyanın Colab'ta bulunması gerekiyor. Soldaki panelden halledilebilir.)**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
!pip freeze "/content/drive/MyDrive/Colab Notebooks/requirements.txt"

absl-py==1.4.0
accelerate==1.5.2
aiohappyeyeballs==2.6.1
aiohttp==3.11.15
aiosignal==1.3.2
alabaster==1.0.0
albucore==0.0.23
albumentations==2.0.5
ale-py==0.10.2
altair==5.5.0
annotated-types==0.7.0
anyio==4.9.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array_record==0.7.1
arviz==0.21.0
astropy==7.0.1
astropy-iers-data==0.2025.4.14.0.37.22
astunparse==1.6.3
atpublic==5.1
attrs==25.3.0
audioread==3.0.1
autograd==1.7.0
babel==2.17.0
backcall==0.2.0
backports.tarfile==1.2.0
beautifulsoup4==4.13.4
betterproto==2.0.0b6
bigframes==1.42.0
bigquery-magics==0.9.0
bleach==6.2.0
blinker==1.9.0
blis==1.3.0
blosc2==3.3.0
bokeh==3.6.3
Bottleneck==1.4.2
bqplot==0.12.44
branca==0.8.1
CacheControl==0.14.2
cachetools==5.5.2
catalogue==2.0.10
certifi==2025.1.31
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.4.1
chex==0.1.89
clarabel==0.10.0
click==8.1.8
cloudpathlib==0.21.0
cloudpickle==3.1.1
cmake==3.31.6
cmdstanpy==1.2.5
colorcet==3.1.0
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confe

In [2]:
import tensorflow as tf
from keras.utils import to_categorical
from keras.models import load_model
import pandas as pd
from sklearn.model_selection import train_test_split

dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/electrical_1.csv')


In [3]:
dataset.columns = dataset.columns.str.strip()
dataset.drop(['Detector'], axis=1, inplace=True)

#Detector string olduğu için bu şekilde iptal edilir

x = dataset.drop(columns=["Status", "Time", "Reading ID"])

#Yukarıdakiler iptal edildikten sonra kalan sütunlar

print(x)
x.shape


      Humidity  Temperature  MQ139  TVOC  eCO2
0         38.2         21.9     69     0   400
1         38.2         21.9     69     0   400
2         38.2         21.9     69     0   400
3         38.2         21.9     68     0   400
4         38.3         21.9     68     0   400
...        ...          ...    ...   ...   ...
1135      41.3         22.3    134  7020  6640
1136      41.3         22.3    134  7115  7190
1137      41.3         22.3    131  7261  6750
1138      41.3         22.3    128  7110  5858
1139      41.3         22.3    128  7144  6100

[1140 rows x 5 columns]


(1140, 5)

In [4]:
y = dataset["Status"]
print(y)
y.shape

0       0
1       0
2       0
3       0
4       0
       ..
1135    2
1136    2
1137    2
1138    2
1139    2
Name: Status, Length: 1140, dtype: int64


(1140,)

In [5]:
#from sklearn.model_selection import train_test_split

#Veri setinin %20'si test olarak ayrılır (test_size=0.2)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [7]:
x_train

Humidity  Temperature  MQ139  TVOC  eCO2
295      39.2         21.9     70   102   450
934      40.9         22.0     79   307   537
565      39.2         22.1     72   139   445
633      40.0         22.1     74   149   454
619      39.3         22.1     72   140   427
..        ...          ...    ...   ...   ...
667      40.5         22.0     74   173   465
884      41.0         22.0     78   227   466
968      41.0         22.1     81   476   612
313      39.3         22.0     70   109   443
981      40.9         22.1     82   521   630

[912 rows x 5 columns]

In [8]:
y_train

295    1
934    1
565    1
633    1
619    1
      ..
667    1
884    1
968    1
313    1
981    1
Name: Status, Length: 912, dtype: int64

In [6]:
x_train

Humidity  Temperature  MQ139  TVOC  eCO2
360       39.2         22.0     71   110   444
1099      40.7         22.2    119  4502  4958
984       40.9         22.1     83   552   680
712       41.0         21.9     75   175   465
233       39.2         21.9     70    77   434
...        ...          ...    ...   ...   ...
708       40.9         22.0     76   177   462
481       39.3         22.1     72   129   436
157       39.0         21.9     69    89   456
1126      41.4         22.3    132  6789  6842
309       39.2         21.9     70   109   457

[912 rows x 5 columns]

In [7]:
#import tensorflow as tf
#from keras.utils import to_categorical

y_train_encoded = to_categorical(y_train)

#Veriler modelin beslenmesi için önceden kodlanır

print(y_train_encoded)
y_train_encoded.shape

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


(912, 3)

In [8]:
model = tf.keras.models.Sequential() #Model tanımlandı

In [9]:
#Modelin katmanları tanımlanır(İlk katman - Input, İkinci katman - Gizli katman, Üçüncü - Output


model.add(tf.keras.layers.Dense(256, input_shape=(5, ), activation='sigmoid'))
model.add(tf.keras.layers.Dense(256, activation='sigmoid'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
#Model derlenir

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [11]:
#Eğitim süreci başlatılır. Epoch sayısı kadar tekrar eder

model.fit(x_train, y_train_encoded, epochs=100)

Epoch 1/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8462 - loss: 0.3916
Epoch 2/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9621 - loss: 0.1190
Epoch 3/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9519 - loss: 0.1314
Epoch 4/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9552 - loss: 0.1063
Epoch 5/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9608 - loss: 0.0908
Epoch 6/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9556 - loss: 0.0921
Epoch 7/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9754 - loss: 0.0701
Epoch 8/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9633 - loss: 0.0704
Epoch 9/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9695 - loss: 0.0660
Epoch 10/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9619 - loss: 0.0736
Epoch 11/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9616 - loss: 0.0827
Epoch 12/100
29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy:

In [13]:
# Ayrıca y_test'i de kodlamak gerekir

y_test_encoded = to_categorical(y_test)
print(y_test_encoded)
y_test_encoded.shape

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

(228, 3)

In [14]:
# Modelin ayrılmış (Önceden bilmediği) test verileri üzerinde denenip verimininin başka veri setleri kullanıldığında
# ne kadar iyi olacağını ölçülmesi. Şayet bu test seti ayrılmaz ise model verilere alışacaktır ve genele uygulanması halinde
# aynı derecede iyi bir performans sergileyemecektir

model.evaluate(x_test, y_test_encoded)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9555 - loss: 0.0871  


[0.08108989149332047, 0.9561403393745422]

In [15]:
model.save('new_model.keras') # Yeni versiyon için gerekli olursa ancak .h5 formatı hala iş görüyor

In [18]:
model.save("new_model.h5") # Modelin kaydedilmesi

In [ ]:
#from keras.models import load_model

# Load the saved model
#loaded_model = load_model("my_model.h5")

In [ ]:
#predictions = model.predict(new_data)

#print(predictions)

#New data için olan kısım diğer programlarda bulunabilir