**Kütüphanelerin ve veri setinin yüklenmesi (Çalıştırmak için öncelikle dosyanın Colab'ta bulunması gerekiyor. Soldaki panelden halledilebilir.)**

In [1]:
import tensorflow as tf
from keras.utils import to_categorical
from keras.models import load_model
import pandas as pd
from sklearn.model_selection import train_test_split

dataset = pd.read_csv('electrical_1.csv')


In [2]:
dataset.columns = dataset.columns.str.strip()
dataset.drop(['Detector'], axis=1, inplace=True)

x = dataset.drop(columns=["Status", "Time", "Reading ID"])

print(x)
x.shape


      Humidity  Temperature  MQ139  TVOC  eCO2
0         38.2         21.9     69     0   400
1         38.2         21.9     69     0   400
2         38.2         21.9     69     0   400
3         38.2         21.9     68     0   400
4         38.3         21.9     68     0   400
...        ...          ...    ...   ...   ...
1135      41.3         22.3    134  7020  6640
1136      41.3         22.3    134  7115  7190
1137      41.3         22.3    131  7261  6750
1138      41.3         22.3    128  7110  5858
1139      41.3         22.3    128  7144  6100

[1140 rows x 5 columns]


(1140, 5)

In [3]:
y = dataset["Status"]
print(y)
y.shape

0       0
1       0
2       0
3       0
4       0
       ..
1135    2
1136    2
1137    2
1138    2
1139    2
Name: Status, Length: 1140, dtype: int64


(1140,)

In [4]:
#from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [5]:
#import tensorflow as tf
#from keras.utils import to_categorical

y_train_encoded = to_categorical(y_train)


In [6]:
model = tf.keras.models.Sequential()

In [7]:
model.add(tf.keras.layers.Dense(256, input_shape=(None, 5), activation='sigmoid'))
model.add(tf.keras.layers.Dense(256, activation='sigmoid'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))

In [8]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [9]:
model.fit(x_train, y_train_encoded, epochs=100)

Epoch 1/100
29/29 [==============================] - 2s 7ms/step - loss: 0.2900 - accuracy: 0.9178
Epoch 2/100
29/29 [==============================] - 0s 5ms/step - loss: 0.1435 - accuracy: 0.9507
Epoch 3/100
29/29 [==============================] - 0s 5ms/step - loss: 0.1155 - accuracy: 0.9507
Epoch 4/100
29/29 [==============================] - 0s 5ms/step - loss: 0.0910 - accuracy: 0.9583
Epoch 5/100
29/29 [==============================] - 0s 5ms/step - loss: 0.0922 - accuracy: 0.9583
Epoch 6/100
29/29 [==============================] - 0s 6ms/step - loss: 0.0910 - accuracy: 0.9616
Epoch 7/100
29/29 [==============================] - 0s 5ms/step - loss: 0.0899 - accuracy: 0.9561
Epoch 8/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0913 - accuracy: 0.9572
Epoch 9/100
29/29 [==============================] - 0s 3ms/step - loss: 0.0866 - accuracy: 0.9550
Epoch 10/100
29/29 [==============================] - 0s 4ms/step - loss: 0.0815 - accuracy: 0.9561
Epoch 11/

In [10]:
y_test_encoded = to_categorical(y_test)
print(y_test_encoded)
y_test_encoded.shape

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

(228, 3)

In [11]:
model.evaluate(x_test, y_test_encoded)

8/8 [==============================] - 0s 3ms/step - loss: 0.0337 - accuracy: 0.9737


[0.03369789943099022, 0.9736841917037964]

In [12]:
model.save('new_model.keras')

In [13]:
model.save("new_model.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
#from keras.models import load_model

# Load the saved model
#loaded_model = load_model("my_model.h5")

In [ ]:
#predictions = model.predict(new_data)

#print(predictions)

#New data için olan kısım diğer programlarda bulunabilir